# on actual server we need to encrypt this using sops or others mechanism
apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-migration-secrets
    namespace: database
stringData:
    db_name: default
    db_host: chi-clickhouse-db-database-0-0.database.svc.cluster.local
    db_password: biuser-password
    db_port: "9000"
    db_user: biuser