---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: db-controller
spec:
  chart:
    spec:
      version: 0.23.3
  values:
    operator:
      resources:
        limits:
          memory: 128Mi
          cpu: 100m
        requests:
          memory: 128Mi
          cpu: 100m