apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: etl-battery-worker-cm
    namespace: etl-workers
    options:
      annotations:
        reloader.stakater.com/match: "true"
    files:
      - ../base/etl-battery-worker.yaml
  - name: etl-orders-worker-cm
    namespace: etl-workers
    options:
      annotations:
        reloader.stakater.com/match: "true"
    files:
      - ../base/etl-orders-worker.yaml

resources:
  - ../base/
  - clickhouse-access-secrets.yaml

patches:
  - path: ./release-etl-battery-worker-patch.yaml
  - path: ./release-etl-orders-worker-patch.yaml