---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etl-battery-worker
  namespace: etl-workers
spec:
  chart:
    spec:
      version: v0.2.24
  values:
    containerImage:
      tag: 4.24
      pullPolicy: Always

    replicaCount: 1
    minPodsAvailable: 0

    containerResources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 128Mi